Document: xlibinput-calibrator
Title: Debian xlibinput-calibrator Manual
Author: <insert document author here>
Abstract: This manual describes what xlibinput-calibrator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xlibinput-calibrator/xlibinput-calibrator.sgml.gz

Format: postscript
Files: /usr/share/doc/xlibinput-calibrator/xlibinput-calibrator.ps.gz

Format: text
Files: /usr/share/doc/xlibinput-calibrator/xlibinput-calibrator.text.gz

Format: HTML
Index: /usr/share/doc/xlibinput-calibrator/html/index.html
Files: /usr/share/doc/xlibinput-calibrator/html/*.html
