

all: uinput-touch-simulation

uinput-touch-simulation: uinput-touch-simulation.c
	gcc -Wall -pedantic -o uinput-touch-simulation uinput-touch-simulation.c

clean:
	rm -f uinput-touch-simulation
	rm -f *.o
